<?php 

	/**
	 * Implements hook_menu().
	 */
	function angupal_menu() {
	  /*
	   *$items['blog'] = array(
	   *  'title' => 'blogs',
	   *  'page callback' => 'blog_page',
	   *  'access arguments' => array('access content'),
	   *  'type' => MENU_SUGGESTED_ITEM,
	   *);
	   */
	  $items['ng'] = array(
	    'title' => 'ng',
	    'page callback' => 'ng_index',
	    'page arguments' => array(),
	    'access arguments' => array(''),
	    'type' => ,
	    'file' => ,
	  );
	
	  return $items;
	}

	function ng_index()
	{
		drupal_get_path('module', 'angupal');
	}