// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var myApp;

  myApp = angular.module('myApp', ['ngCookies', 'ngResource', 'ngSanitize']);

  Mousetrap.bind('a d m i n', function() {
    return window.location = base_path + 'admin/content';
  });

}).call(this);
