// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  angular.module('myApp').controller('officeCtrl', [
    '$scope', 'officeService', function($scope, service) {
      $scope.test = 3;
      $scope.data = {};
      service.getBlaise().then(function(data) {
        return $scope.data.blaise = data.data;
      });
      return service.getDidier().then(function(data) {
        return $scope.data.didier = data.data;
      });
    }
  ]).controller('projectCtrl', [
    '$scope', 'projectService', function($scope, service) {
      $scope.data = {};
      service.getProjects().then(function(data) {
        return $scope.data.projects = data.data.nodes;
      });
      return service.getMasai().then(function(data) {
        return $scope.data.masai = data.data.nodes[0].node;
      });
    }
  ]).controller('testCtrl', function($scope) {
    return $scope.test = 3;
  });

}).call(this);
