// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  angular.module('myApp').controller('mainCtrl', function($scope, $timeout) {
    $scope.swipers = {
      vertical: null,
      horz: new Array
    };
    $scope.data = {};
    return $scope.initPagers = function() {
      return $timeout(function() {
        var classes, i, item, pager, pagers, pagination, slideNames, _i, _j, _len, _len1, _ref;

        console.log($scope.swipers.vertPagination);
        slideNames = new Array;
        _ref = $scope.swipers.vertical.slides;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          pager = _ref[_i];
          slideNames.push(pager.attributes['data-name'].value);
        }
        pagination = angular.element('.vert-pagination');
        pagers = pagination.find('div.vert-pager');
        for (i = _j = 0, _len1 = pagers.length; _j < _len1; i = ++_j) {
          item = pagers[i];
          classes = angular.element(item).attr('class') + ' vert-pager';
          console.log(classes);
          $(item).attr('data-title', slideNames[i]).append($('<div class="vert-pager-dot></div>'));
        }
        return pagination.remove;
      }, 1000);
    };
  }).controller('officeCtrl', [
    '$scope', 'officeService', function($scope, service) {
      $scope.data = {};
      service.getBlaise().then(function(data) {
        return $scope.data.blaise = data.data;
      });
      return service.getDidier().then(function(data) {
        return $scope.data.didier = data.data;
      });
    }
  ]).controller('projectCtrl', [
    '$scope', 'projectService', function($scope, service) {
      $scope.data = {};
      service.getProjects().then(function(data) {
        return $scope.data.projects = data.data.nodes;
      });
      return service.getMasai().then(function(data) {
        return $scope.data.masai = data.data.nodes[0].node;
      });
    }
  ]);

}).call(this);
