// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('myApp').directive("myProject", [
    function() {
      return {
        scope: {
          project: "=myProject"
        },
        replace: true,
        templateUrl: "views/project.html"
      };
    }
  ]).directive("myBio", [
    function() {
      return {
        scope: {
          bio: "=myBio"
        },
        templateUrl: "views/bio.html"
      };
    }
  ]).directive("swiper", [
    '$timeout', function($timeout) {
      return {
        controller: function($scope) {
          return $scope.horizontal = new Array;
        },
        priority: 500,
        link: function(scope, elem, attrs) {
          return $timeout(function() {
            var $this, options;

            console.log(attrs.swiper, angular.element(elem));
            options = {
              mousewheelControl: true,
              mousewheelControlForceToAxis: true,
              keyboardControl: true,
              resizeReInit: true,
              grabCursor: true
            };
            if (attrs.swiper === 'vert') {
              options.slideClass = 'slide-vert';
              options.mode = 'vertical';
              $this = angular.element(elem);
              scope.vertical = $this.swiper(options);
              return;
            } else {
              options.slideClass = 'slide-horz';
              $this = angular.element(elem);
            }
            if (attrs.settings === 'bio') {
              options.scrollContainer = true;
            }
            return scope.horizontal.push($this.swiper(options));
          }, 1000);
        }
      };
    }
  ]);

}).call(this);
