// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  angular.module('myApp', ['ngResource']).service('officeService', [
    '$http', function($http) {
      var get;

      this.getBlaise = function() {
        return get('node/1.json');
      };
      this.getDidier = function() {
        return get('node/2.json');
      };
      get = function(url) {
        var data;

        return data = $http({
          url: base_path + url,
          method: 'GET'
        });
      };
      return this;
    }
  ]);

  angular.module('myApp', ['ngResource']).controller('officeCtrl', [
    '$scope', 'officeService', function($scope, service) {
      $scope.bio = {};
      service.getBlaise().then(function(data) {
        console.log(data);
        return $scope.bio.blaise = data.data;
      });
      return service.getDidier().then(function(data) {
        console.log(data);
        return $scope.bio.didier = data.data;
      });
    }
  ]);

}).call(this);
