// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  angular.module('myApp', ['ngResource']).service('drupal', [
    '$http', function($http) {
      var auth, getAuth;

      auth = null;
      getAuth = function() {
        if (auth) {
          return auth;
        } else {
          return $http({
            url: drupal_path + 'user',
            method: 'GET'
          });
        }
      };
      return this.auth = function() {
        return getAuth();
      };
    }
  ]).service('officeService', [
    '$http', function($http) {
      var get;

      this.getBlaise = function() {
        return get('node/1.json');
      };
      this.getDidier = function() {
        return get('node/2.json');
      };
      get = function(url) {
        var data;

        return data = $http({
          url: drupal_path + url,
          method: 'GET'
        });
      };
      return this;
    }
  ]).service('nodeService', [
    '$http', function($http) {
      var get;

      this.getNode = function(nid) {
        return get('node/' + nid + '.json');
      };
      get = function(url) {
        var data;

        return data = $http({
          url: drupal_path + url,
          method: 'GET'
        });
      };
      return this;
    }
  ]).service('projectService', [
    '$http', function($http) {
      var get;

      this.getMasai = function() {
        return get('node/4/project.json');
      };
      this.getProjects = function() {
        return get('projects.json');
      };
      get = function(url) {
        var data;

        return data = $http({
          url: drupal_path + url,
          method: 'GET'
        });
      };
      return this;
    }
  ]);

}).call(this);
